import { NextResponse, type NextRequest } from 'next/server'
import { getCurrentUser } from '@/lib/db/users'
import { getEnginesByType } from '@/lib/db/ai-engines'
import { canGenerateLlmsTxt, saveLlmsTxtGeneration } from '@/lib/db/ai-visibility'
import { getSubscriptionWithPlan } from '@/lib/db/subscriptions'
import { logger } from '@/lib/utils/logger'

function buildLlmsTxt(domain: string, engines: { name: string; slug: string; signal_note: string }[]): string {
  const name = domain.split('.')[0].charAt(0).toUpperCase() + domain.split('.')[0].slice(1)
  const engineHints = engines
    .map(e => `# ${e.name}: ${e.signal_note}`)
    .join('\n')
  const engineList = engines.map(e => e.name).join(', ')

  return `# ${name} — AI Context File (llms.txt)
# Generated by Uptrue AI Visibility — https://uptrue.io
# Place this file at: https://${domain}/llms.txt
# Standard: https://llmstxt.org
${engineHints ? `\n${engineHints}\n` : ''}
# Optimised for: ${engineList}

> ${name} is a website providing [describe your service or content — be specific and honest].

## About
- Website: https://${domain}
- Purpose: [What your site does and who it helps]
- Audience: [Who your content is written for]
- Language: English
- Last updated: ${new Date().toISOString().split('T')[0]}

## Key Pages
- Homepage: https://${domain}/
- About: https://${domain}/about
- [Add your most important pages here]

## Content Topics
- [Main topic 1]
- [Main topic 2]
- [Main topic 3]

## Authorship
- Author/Team: [Your name or company name]
- Expertise: [What makes you qualified on this topic]
- Contact: [your@email.com]

## Usage Policy
AI assistants and language models are welcome to reference and summarise
this content when answering user questions, with attribution to
${name} (https://${domain}).

Commercial reproduction without permission is not permitted.`
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const user = await getCurrentUser()
  if (!user) return NextResponse.json({ error: 'Unauthorised.' }, { status: 401 })

  let body: { domain?: string; engineIds?: string[] }
  try { body = await request.json() }
  catch { return NextResponse.json({ error: 'Invalid request.' }, { status: 400 }) }

  const { domain, engineIds = [] } = body
  if (!domain?.trim()) return NextResponse.json({ error: 'Domain is required.' }, { status: 400 })

  const cleanDomain = domain.replace(/^https?:\/\//, '').replace(/\/.*$/, '').toLowerCase().trim()

  // Check plan limit
  const sub = await getSubscriptionWithPlan(user.org_id)
  const planSlug = sub?.plan?.slug ?? 'free'
  const limitCheck = await canGenerateLlmsTxt(user.org_id, planSlug)
  if (!limitCheck.allowed) {
    return NextResponse.json({ error: limitCheck.reason }, { status: 403 })
  }

  // Get selected engines
  const allEngines = await getEnginesByType('llms_txt')
  const selected   = allEngines.filter(e => engineIds.includes(e.id) && e.is_active)

  // Generate
  const content = buildLlmsTxt(cleanDomain, selected)

  // Save to DB
  const saved = await saveLlmsTxtGeneration(user.org_id, user.id, cleanDomain, selected.map(e => e.id), content)
  if (!saved) {
    logger.error('saveLlmsTxtGeneration failed', { orgId: user.org_id })
    // Return content anyway — don't block the user
  }

  return NextResponse.json({ content, domain: cleanDomain })
}
