stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - npx vercel@latest pull --yes --environment=production --token=$VERCEL_TOKEN
    - npx vercel@latest build --token=$VERCEL_TOKEN
    - npx vercel@latest deploy --prebuilt --token=$VERCEL_TOKEN
  only:
    - dev
  environment:
    name: development
    url: https://uptrue-dev.vercel.app

deploy_prod:
  stage: deploy
  script:
    - npx vercel@latest pull --yes --environment=production --token=$VERCEL_TOKEN
    - npx vercel@latest build --prod --token=$VERCEL_TOKEN
    - npx vercel@latest deploy --prebuilt --prod --token=$VERCEL_TOKEN
  only:
    - master
  environment:
    name: production
    url: https://uptrue.vercel.app
