stages:
  - deploy

deploy_dev:
  stage: deploy
  script:
    - npx --yes vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - npx --yes vercel build --token=$VERCEL_TOKEN
    - DEPLOYMENT_URL=$(npx --yes vercel deploy --prebuilt --token=$VERCEL_TOKEN --meta gitBranch=$CI_COMMIT_REF_NAME --meta gitCommitSha=$CI_COMMIT_SHA)
    - npx --yes vercel alias $DEPLOYMENT_URL dev.uptrue.io --token=$VERCEL_TOKEN
  only:
    - dev
  environment:
    name: development
    url: https://dev.uptrue.io

deploy_prod:
  stage: deploy
  script:
    - npx --yes vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - npx --yes vercel build --prod --token=$VERCEL_TOKEN
    - npx --yes vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN --meta gitBranch=$CI_COMMIT_REF_NAME --meta gitCommitSha=$CI_COMMIT_SHA
  only:
    - master
  environment:
    name: production
    url: https://uptrue.io
