'use client'

import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import type { AiSeoCheckResult, CheckResult, CategoryScore } from '@/app/api/tools/ai-seo-check/route'

function ScoreRing({ score }: { score: number }) {
  const color = score >= 75 ? '#22c55e' : score >= 45 ? '#f59e0b' : '#ef4444'
  const label = score >= 75 ? 'Good' : score >= 45 ? 'Needs Work' : 'Poor'
  const circumference = 2 * Math.PI * 40
  const offset = circumference - (score / 100) * circumference
  return (
    <div className="ai-score-ring-wrapper">
      <svg width="100" height="100" viewBox="0 0 100 100">
        <circle cx="50" cy="50" r="40" fill="none" stroke="var(--border-primary)" strokeWidth="8" />
        <circle cx="50" cy="50" r="40" fill="none" stroke={color} strokeWidth="8"
          strokeDasharray={circumference} strokeDashoffset={offset} strokeLinecap="round"
          transform="rotate(-90 50 50)" style={{ transition: 'stroke-dashoffset 1s ease' }} />
        <text x="50" y="46" textAnchor="middle" fill={color} fontSize="20" fontWeight="800">{score}</text>
        <text x="50" y="60" textAnchor="middle" fill="var(--text-muted)" fontSize="9">/100</text>
      </svg>
      <div className="ai-score-label" style={{ color }}>{label}</div>
    </div>
  )
}

function CategoryBar({ cat }: { cat: CategoryScore }) {
  const pct = Math.round((cat.score / cat.max) * 100)
  const color = pct >= 75 ? '#22c55e' : pct >= 45 ? '#f59e0b' : '#ef4444'
  return (
    <div className="ai-cat-bar">
      <div className="ai-cat-bar-header">
        <span className="ai-cat-bar-name">{cat.name}</span>
        <span className="ai-cat-bar-score" style={{ color }}>{cat.score}/{cat.max}</span>
      </div>
      <div className="ai-cat-bar-track">
        <div className="ai-cat-bar-fill" style={{ width: `${pct}%`, background: color }} />
      </div>
    </div>
  )
}

const SCAN_STEPS = [
  'Fetching robots.txt...',
  'Checking AI bot permissions...',
  'Scanning structured data...',
  'Analysing content signals...',
  'Checking trust & authority...',
  'Measuring page performance...',
]

export function AiSeoCheckerTool() {
  const [url, setUrl]         = useState('')
  const [loading, setLoading] = useState(false)
  const [stepIdx, setStepIdx] = useState(0)
  const [result, setResult]   = useState<AiSeoCheckResult | null>(null)
  const [error, setError]     = useState('')
  const [activeTab, setActiveTab] = useState<'overview' | 'crawlers' | 'checklist' | 'llms'>('overview')
  const [copied, setCopied]   = useState(false)
  const [isLoggedIn, setIsLoggedIn] = useState(false)

  useEffect(() => {
    const supabase = createClient()
    supabase.auth.getSession().then(({ data: { session } }) => {
      setIsLoggedIn(!!session)
    })
  }, [])

  async function handleCheck(e: React.FormEvent) {
    e.preventDefault()
    if (!url.trim()) return
    setLoading(true)
    setResult(null)
    setError('')
    setStepIdx(0)

    // Animate scan steps while waiting
    const stepInterval = setInterval(() => {
      setStepIdx(i => Math.min(i + 1, SCAN_STEPS.length - 1))
    }, 400)

    try {
      const res = await fetch('/api/tools/ai-seo-check', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: url.trim() }),
      })
      const data = await res.json()
      if (!res.ok) {
        setError(data.error ?? 'Something went wrong. Please try again.')
      } else {
        setResult(data as AiSeoCheckResult)
        setActiveTab('overview')
      }
    } catch {
      setError('Could not complete the check. Please try again.')
    } finally {
      clearInterval(stepInterval)
      setLoading(false)
    }
  }

  function copyLlmsTxt(content: string) {
    navigator.clipboard.writeText(content)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const failedChecks = result?.checks.filter(c => !c.passed) ?? []
  const passedChecks = result?.checks.filter(c => c.passed) ?? []

  // Generate basic llms.txt preview (first 6 lines — rest gated behind signup)
  function getLlmsPreview(domain: string): string {
    const name = domain.split('.')[0].charAt(0).toUpperCase() + domain.split('.')[0].slice(1)
    return `# ${name} — AI Context File (llms.txt)
# Generated by Upnotify AI SEO Checker
# Place at: https://${domain}/llms.txt

> ${name} is a website providing [your description here].

## About
- Website: https://${domain}
[Sign up free to generate your full customised file →]`
  }

  return (
    <div className="ai-checker-wrapper">

      {/* Input */}
      <form onSubmit={handleCheck} className="ai-checker-form">
        <div className="ai-checker-input-row">
          <input type="url" value={url} onChange={e => setUrl(e.target.value)}
            placeholder="https://yourwebsite.com" className="ai-checker-input" required />
          <button type="submit" className="ai-checker-btn" disabled={loading}>
            {loading
              ? <span className="ai-checker-loading"><span className="ai-spinner" /> Scanning...</span>
              : 'Check AI Readiness'}
          </button>
        </div>
        <p className="ai-checker-hint">Free — no signup required. We fetch your page to run this check.</p>
      </form>

      {/* Error */}
      {error && <div className="ai-checker-error">{error}</div>}

      {/* Loading */}
      {loading && (
        <div className="ai-checker-scanning">
          <div className="ai-scanning-steps">
            {SCAN_STEPS.map((step, i) => (
              <div key={step} className={`ai-scanning-step ${i < stepIdx ? 'ai-step-done' : i === stepIdx ? 'ai-step-active' : ''}`}>
                {step}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Results */}
      {result && (
        <div className="ai-checker-results">

          {/* Score header */}
          <div className="ai-results-header">
            <ScoreRing score={result.score} />
            <div className="ai-results-summary">
              <h2 className="ai-results-domain">{result.domain}</h2>
              <p className="ai-results-subtitle">AI Readiness Score · {result.responseTimeMs}ms · {result.pageSizeKb}KB</p>
              <div className="ai-results-stats">
                <span className="ai-stat-pass">{passedChecks.length} passed</span>
                <span className="ai-stat-dot">·</span>
                <span className="ai-stat-fail">{failedChecks.length} need fixing</span>
              </div>
              <div className="ai-cat-bars">
                {result.categories.map(cat => <CategoryBar key={cat.name} cat={cat} />)}
              </div>
            </div>
          </div>

          {/* Tabs */}
          <div className="ai-tabs">
            {([
              ['overview',  'Overview'],
              ['crawlers',  'AI Crawlers'],
              ['checklist', `Issues (${failedChecks.length})`],
              ['llms',      'llms.txt'],
            ] as const).map(([tab, label]) => (
              <button key={tab} className={`ai-tab${activeTab === tab ? ' ai-tab-active' : ''}`}
                onClick={() => setActiveTab(tab)}>{label}</button>
            ))}
          </div>

          {/* Overview tab */}
          {activeTab === 'overview' && (
            <div className="ai-tab-content">
              <div className="ai-overview-grid">
                {result.categories.map(cat => {
                  const catChecks = result.checks.filter(c => c.category === cat.name)
                  const fails = catChecks.filter(c => !c.passed)
                  const pct = Math.round((cat.score / cat.max) * 100)
                  const color = pct >= 75 ? '#22c55e' : pct >= 45 ? '#f59e0b' : '#ef4444'
                  return (
                    <div key={cat.name} className="ai-overview-card">
                      <div className="ai-overview-card-header">
                        <span className="ai-overview-cat-name">{cat.name}</span>
                        <span className="ai-overview-cat-score" style={{ color }}>{cat.score}/{cat.max}</span>
                      </div>
                      {fails.length === 0
                        ? <p className="ai-overview-all-pass">All checks passed</p>
                        : <ul className="ai-overview-fails">
                            {fails.slice(0, 3).map(f => (
                              <li key={f.id} className="ai-overview-fail-item">✗ {f.label}</li>
                            ))}
                            {fails.length > 3 && <li className="ai-overview-fail-more">+{fails.length - 3} more</li>}
                          </ul>
                      }
                    </div>
                  )
                })}
              </div>

              {/* Top 3 quick wins */}
              {failedChecks.length > 0 && (
                <div className="ai-quick-wins">
                  <h3 className="ai-quick-wins-title">Top fixes to improve your score</h3>
                  {failedChecks.slice(0, 3).map(c => (
                    <div key={c.id} className="ai-quick-win-item">
                      <span className="ai-quick-win-pts">+{c.points}pts</span>
                      <div>
                        <div className="ai-quick-win-label">{c.label}</div>
                        <div className="ai-quick-win-fix">{c.fix}</div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Crawlers tab */}
          {activeTab === 'crawlers' && (
            <div className="ai-tab-content">
              <p className="ai-tab-intro">
                Each AI engine sends its own crawler. Here&apos;s which ones can currently index <strong>{result.domain}</strong>:
              </p>
              <div className="ai-crawlers-grid">
                {result.crawlers.map(c => (
                  <div key={c.slug} className={`ai-crawler-card ${c.allowed ? 'ai-crawler-allowed' : 'ai-crawler-blocked'}`}>
                    <div className="ai-crawler-header">
                      <span className="ai-crawler-name">{c.name}</span>
                      <span className={`ai-crawler-status ${c.allowed ? 'ai-status-allowed' : 'ai-status-blocked'}`}>
                        {c.allowed ? '✓ Allowed' : '✗ Blocked'}
                      </span>
                    </div>
                    <div className="ai-crawler-note">{c.note}</div>
                  </div>
                ))}
              </div>
              {result.crawlers.filter(c => !c.allowed).length > 0 && (
                <div className="ai-crawler-fix-box">
                  <strong>How to fix:</strong> Open your <code>robots.txt</code> and add <code>Allow: /</code> rules for each blocked bot, or remove any <code>Disallow: /</code> rules that apply to them.
                </div>
              )}
            </div>
          )}

          {/* Checklist tab */}
          {activeTab === 'checklist' && (
            <div className="ai-tab-content">
              {failedChecks.length > 0 && (
                <>
                  <p className="ai-tab-intro">{failedChecks.length} issues found — fix these to improve your AI visibility score.</p>
                  <div className="ai-checklist">
                    {failedChecks.map(item => (
                      <div key={item.id} className="ai-check-item ai-check-fail">
                        <div className="ai-check-left">
                          <span className="ai-check-icon ai-icon-fail">✗</span>
                          <div>
                            <div className="ai-check-label">{item.label}</div>
                            <div className="ai-check-fix">{item.fix}</div>
                          </div>
                        </div>
                        <span className="ai-check-points">+{item.points}pts</span>
                      </div>
                    ))}
                  </div>
                </>
              )}
              {passedChecks.length > 0 && (
                <>
                  <p className="ai-tab-intro" style={{ marginTop: failedChecks.length > 0 ? 24 : 0 }}>
                    {passedChecks.length} checks already passing — well done.
                  </p>
                  <div className="ai-checklist">
                    {passedChecks.map(item => (
                      <div key={item.id} className="ai-check-item ai-check-pass">
                        <div className="ai-check-left">
                          <span className="ai-check-icon ai-icon-pass">✓</span>
                          <div className="ai-check-label">{item.label}</div>
                        </div>
                        <span className="ai-check-points">+{item.points}pts</span>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          )}

          {/* llms.txt tab — gated */}
          {activeTab === 'llms' && (
            <div className="ai-tab-content">
              <p className="ai-tab-intro">
                <strong>llms.txt</strong> tells AI engines what your site is about and how to use your content.
                Place it at <code>https://{result.domain}/llms.txt</code>.
              </p>

              {/* Preview — blurred after line 6 */}
              <div className="ai-llms-preview-wrapper">
                <div className="ai-llms-box">
                  <div className="ai-llms-header">
                    <span>/llms.txt — preview for {result.domain}</span>
                    <button className="ai-copy-btn" onClick={() => copyLlmsTxt(getLlmsPreview(result.domain))}>
                      {copied ? '✓ Copied' : 'Copy preview'}
                    </button>
                  </div>
                  <pre className="ai-llms-content">{getLlmsPreview(result.domain)}</pre>
                </div>
                <div className="ai-llms-gate">
                  <div className="ai-llms-gate-inner">
                    {isLoggedIn ? (
                      <>
                        <div className="ai-llms-gate-icon">✨</div>
                        <h3 className="ai-llms-gate-title">Generate your full llms.txt</h3>
                        <p className="ai-llms-gate-desc">
                          Generate a complete llms.txt tailored to your site from your Upnotify dashboard.
                        </p>
                        <a href="/dashboard/ai-visibility" className="ai-llms-gate-btn">Go to AI Visibility →</a>
                      </>
                    ) : (
                      <>
                        <div className="ai-llms-gate-icon">🔒</div>
                        <h3 className="ai-llms-gate-title">Get your full customised llms.txt</h3>
                        <p className="ai-llms-gate-desc">
                          Sign up free to generate a complete llms.txt tailored to your site and
                          selected AI engines — Perplexity, ChatGPT, Claude, Gemini, and more.
                        </p>
                        <a href="/signup" className="ai-llms-gate-btn">Sign up free — it takes 30 seconds</a>
                        <p className="ai-llms-gate-sub">No credit card. Free plan includes 1 generation.</p>
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Monitor CTA */}
          <div className="ai-monitor-cta">
            <div className="ai-monitor-cta-left">
              <div className="ai-monitor-cta-badge">NEW</div>
              <div>
                <div className="ai-monitor-cta-title">Monitor your AI citations — ongoing</div>
                <div className="ai-monitor-cta-desc">
                  Track whether Perplexity, ChatGPT, and Gemini are citing your site for your target keywords.
                  Get alerted when you gain or lose AI visibility.
                </div>
              </div>
            </div>
            <a href="/signup" className="ai-monitor-cta-btn">Start free →</a>
          </div>

        </div>
      )}
    </div>
  )
}
