'use client'

import Link from 'next/link'

export function ReportAiSummary({ summary }: { summary: string }): React.ReactElement {
  return (
    <div className="report-ai-card" style={{ marginBottom: 24 }}>
      <div className="card">
        <div className="card-header">
          <div className="card-title" style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            AI Executive Summary
          </div>
        </div>
        <div className="card-content">
          <div style={{ fontSize: 15, lineHeight: 1.8, color: '#475569', whiteSpace: 'pre-wrap' }}>
            {summary}
          </div>
          <div className="ai-disclaimer-notice">
            This summary was generated by AI and is provided for informational purposes only. AI can
            make mistakes — please verify important information independently.{' '}
            <Link href="/ai-disclaimer">Learn more</Link>
          </div>
        </div>
      </div>
    </div>
  )
}
