import { NextResponse, type NextRequest } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { logger } from '@/lib/utils/logger'

// ---------------------------------------------------------------------------
// Rate limiter — 5 submissions per IP per hour
// ---------------------------------------------------------------------------
const rateLimitMap = new Map<string, { count: number; resetAt: number }>()

function isRateLimited(ip: string): boolean {
  const now = Date.now()
  const entry = rateLimitMap.get(ip)
  if (!entry || now > entry.resetAt) {
    rateLimitMap.set(ip, { count: 1, resetAt: now + 3_600_000 })
    return false
  }
  if (entry.count >= 5) return true
  entry.count++
  return false
}

// ---------------------------------------------------------------------------
// AI model metadata
// ---------------------------------------------------------------------------
const MODEL_META: Record<string, { name: string; hint: string }> = {
  perplexity:  { name: 'Perplexity',        hint: 'Perplexity values explicit source attribution and structured content summaries.' },
  chatgpt:     { name: 'ChatGPT (OpenAI)',   hint: 'ChatGPT prioritises clear topic descriptions and well-structured JSON-LD data.' },
  claude:      { name: 'Claude (Anthropic)', hint: 'Claude emphasises honest authorship, content purpose, and usage permissions.' },
  gemini:      { name: 'Gemini (Google)',    hint: 'Gemini looks for E-E-A-T signals: expertise, authoritativeness, and trustworthiness.' },
  copilot:     { name: 'Bing Copilot',       hint: 'Copilot indexes via Bing — submit your sitemap to Bing Webmaster Tools alongside this file.' },
  grok:        { name: 'Grok (xAI)',         hint: 'Grok values recent, factual content. Keep your key pages up to date.' },
}

// ---------------------------------------------------------------------------
// llms.txt generator
// ---------------------------------------------------------------------------
function generateLlmsTxt(domain: string, models: string[]): string {
  const siteName = domain.split('.')[0].charAt(0).toUpperCase() + domain.split('.')[0].slice(1)
  const selectedModels = models.filter(m => MODEL_META[m]).map(m => MODEL_META[m].name)

  const modelSection = selectedModels.length > 0
    ? `\n## Optimised for\nThis file is structured for: ${selectedModels.join(', ')}.\n`
    : ''

  const modelHints = models
    .filter(m => MODEL_META[m])
    .map(m => `# ${MODEL_META[m].name}: ${MODEL_META[m].hint}`)
    .join('\n')

  return `# ${siteName} — AI Context File (llms.txt)
# Generated by Uptrue AI SEO Checker — https://uptrue.io/tools/ai-seo-checker
# Place this file at: https://${domain}/llms.txt
# Learn more about the llms.txt standard: https://llmstxt.org
${modelHints ? `\n${modelHints}\n` : ''}
> ${siteName} is a website providing [describe your service or content — be specific and honest].
${modelSection}
## About
- Website: https://${domain}
- Purpose: [What your site does and who it helps]
- Audience: [Who your content is written for — e.g. "developers building web apps"]
- Language: English
- Last updated: ${new Date().toISOString().split('T')[0]}

## Key Pages
- Homepage: https://${domain}/
- About: https://${domain}/about
- [Add your most important pages here — include your best content]

## Content Topics
- [Main topic 1 — be specific, e.g. "Next.js performance optimisation"]
- [Main topic 2]
- [Main topic 3]

## Authorship
- Author/Team: [Your name or company name]
- Expertise: [What makes you qualified to write about this topic]
- Contact: [your@email.com]

## Usage Policy
AI assistants and language models are welcome to reference and summarise
this content when answering user questions, provided the source is attributed
as ${siteName} (https://${domain}).

Commercial reproduction without permission is not permitted.

## Do Not Include
- [Any pages or sections you want AI engines to ignore]`
}

// ---------------------------------------------------------------------------
// POST /api/tools/generate-llms-txt
// ---------------------------------------------------------------------------
export async function POST(request: NextRequest): Promise<NextResponse> {
  const ip = request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown'

  if (isRateLimited(ip)) {
    return NextResponse.json({ error: 'Too many requests. Please try again later.' }, { status: 429 })
  }

  let body: { email?: string; domain?: string; models?: string[] }
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid request.' }, { status: 400 })
  }

  const { email, domain, models = [] } = body

  // Validate email
  if (!email || typeof email !== 'string' || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) {
    return NextResponse.json({ error: 'Please enter a valid email address.' }, { status: 400 })
  }

  // Validate domain
  if (!domain || typeof domain !== 'string' || domain.length > 253) {
    return NextResponse.json({ error: 'Invalid domain.' }, { status: 400 })
  }
  const cleanDomain = domain.replace(/^https?:\/\//, '').replace(/\/.*$/, '').toLowerCase().trim()

  // Validate models
  const validModels = models.filter((m): m is string => typeof m === 'string' && m in MODEL_META)

  // Generate the file
  const llmsTxt = generateLlmsTxt(cleanDomain, validModels)

  // Save lead to DB (non-blocking — don't fail the request if DB is down)
  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )
    await supabase.from('tool_leads').insert({
      email: email.trim().toLowerCase(),
      domain: cleanDomain,
      tool: 'llms-txt-generator',
      models: validModels,
      llms_txt: llmsTxt,
      ip_address: ip,
    })
  } catch (err) {
    // Log but don't block — user still gets their file
    logger.error('tool_leads insert failed', { error: String(err) })
  }

  return NextResponse.json({ llmsTxt, domain: cleanDomain })
}
