'use client'

import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { Suspense, useState } from 'react'
import type { UnifiedPost } from './page'

const POSTS_PER_PAGE = 9

const CATEGORIES = ['All', 'Guide', 'WordPress', 'Hosting', 'Ecommerce', 'Security', 'Performance', 'Agency', 'Outage']

function BlogIndexContent({ posts }: { posts: UnifiedPost[] }) {
  const searchParams = useSearchParams()
  const router = useRouter()
  const page = Math.max(1, parseInt(searchParams.get('page') ?? '1', 10))
  const [activeCategory, setActiveCategory] = useState('All')
  const [searchQuery, setSearchQuery] = useState('')

  const filtered = posts.filter(p => {
    const matchesCategory = activeCategory === 'All' || p.category === activeCategory
    const matchesSearch = searchQuery === '' ||
      p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.excerpt.toLowerCase().includes(searchQuery.toLowerCase())
    return matchesCategory && matchesSearch
  })

  const featuredPost = filtered[0]
  const remainingPosts = filtered.slice(1)

  const totalPages = Math.ceil(remainingPosts.length / POSTS_PER_PAGE)
  const start = (page - 1) * POSTS_PER_PAGE
  const pagePosts = remainingPosts.slice(start, start + POSTS_PER_PAGE)

  function goToPage(p: number) {
    const params = new URLSearchParams(searchParams.toString())
    if (p === 1) {
      params.delete('page')
    } else {
      params.set('page', String(p))
    }
    router.push(`/blog${params.size > 0 ? `?${params.toString()}` : ''}`)
  }

  function handleCategoryChange(cat: string) {
    setActiveCategory(cat)
    router.push('/blog')
  }

  function handleSearch(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault()
    const fd = new FormData(e.currentTarget)
    setSearchQuery(fd.get('q') as string ?? '')
  }

  return (
    <div className="blog-index">
      {/* Hero */}
      <div className="blog-hero-section">
        <div className="blog-hero-inner">
          <span className="blog-hero-eyebrow">Uptrue Blog</span>
          <h1 className="blog-hero-title">Uptime, monitoring &amp; WordPress guides</h1>
          <p className="blog-hero-subtitle">
            Real-world fixes, monitoring tips, outage reports, and performance guides for developers, agencies, and site owners.
          </p>
          <form className="blog-hero-search" onSubmit={handleSearch}>
            <input
              className="blog-hero-search-input"
              name="q"
              type="text"
              placeholder="Search articles..."
              defaultValue={searchQuery}
            />
            <button type="submit" className="blog-hero-search-btn">Search</button>
          </form>
        </div>
      </div>

      {/* Filter tabs */}
      <div className="blog-filter-bar">
        <div className="blog-filter-inner">
          {CATEGORIES.map(cat => (
            <button
              key={cat}
              className={`blog-filter-tab${activeCategory === cat ? ' active' : ''}`}
              onClick={() => handleCategoryChange(cat)}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      <div className="blog-content-area">
        {filtered.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '64px 0', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 40, marginBottom: 16 }}>🔍</div>
            <p style={{ fontSize: 16 }}>No articles found. Try a different search or category.</p>
          </div>
        ) : (
          <>
            {/* Featured post */}
            {featuredPost && page === 1 && (
              <div className="blog-featured-section">
                <div className="blog-featured-label">Featured Article</div>
                <Link href={`/blog/${featuredPost.slug}`} className="blog-featured-card">
                  <div className="blog-featured-visual">
                    <span className="blog-featured-category">{featuredPost.category}</span>
                    <div className="blog-featured-visual-title">{featuredPost.title}</div>
                  </div>
                  <div className="blog-featured-content">
                    <div className="blog-featured-excerpt">{featuredPost.excerpt}</div>
                    <div className="blog-featured-meta">
                      <span>{featuredPost.displayDate}</span>
                      <span className="blog-featured-meta-dot" />
                      <span>{featuredPost.readTime}</span>
                      {featuredPost.isAutoGenerated && (
                        <>
                          <span className="blog-featured-meta-dot" />
                          <span style={{ color: '#dc2626', fontWeight: 700, fontSize: 11, textTransform: 'uppercase' }}>Live</span>
                        </>
                      )}
                    </div>
                    <span className="blog-featured-read-more">Read article →</span>
                  </div>
                </Link>
              </div>
            )}

            {/* Article grid */}
            {pagePosts.length > 0 && (
              <>
                <div className="blog-section-label">
                  {activeCategory === 'All' ? 'All Articles' : activeCategory}
                  {' '}({filtered.length - (page === 1 ? 1 : 0)} articles)
                </div>
                <div className="blog-posts-grid">
                  {pagePosts.map(post => (
                    <Link key={post.slug} href={`/blog/${post.slug}`} className="blog-post-card">
                      <div className="blog-post-card-body">
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <span className="blog-post-category">{post.category}</span>
                          {post.isAutoGenerated && (
                            <span style={{
                              display: 'inline-block', fontSize: '11px', fontWeight: 600,
                              color: '#dc2626', background: 'rgba(220,38,38,0.08)',
                              padding: '2px 8px', borderRadius: '20px', textTransform: 'uppercase' as const,
                              letterSpacing: '0.5px',
                            }}>Live</span>
                          )}
                        </div>
                        <div className="blog-post-card-title">{post.title}</div>
                        <div className="blog-post-card-excerpt">{post.excerpt}</div>
                        <div className="blog-post-card-meta">
                          <span>{post.displayDate}</span>
                          <span className="blog-post-card-dot" />
                          <span>{post.readTime}</span>
                        </div>
                      </div>
                    </Link>
                  ))}
                </div>
              </>
            )}

            {/* Pagination */}
            {totalPages > 1 && (
              <div className="blog-pagination">
                <button
                  onClick={() => goToPage(page - 1)}
                  disabled={page <= 1}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 16px',
                    background: 'none', border: '1px solid var(--border-primary)', borderRadius: '8px',
                    color: page <= 1 ? 'var(--text-muted)' : 'var(--text-primary)',
                    cursor: page <= 1 ? 'not-allowed' : 'pointer', fontSize: '14px', fontWeight: 500,
                    opacity: page <= 1 ? 0.5 : 1,
                  }}
                >← Newer</button>
                <span className="blog-pagination-info">Page {page} of {totalPages}</span>
                <button
                  onClick={() => goToPage(page + 1)}
                  disabled={page >= totalPages}
                  style={{
                    display: 'flex', alignItems: 'center', gap: '6px', padding: '8px 16px',
                    background: 'none', border: '1px solid var(--border-primary)', borderRadius: '8px',
                    color: page >= totalPages ? 'var(--text-muted)' : 'var(--text-primary)',
                    cursor: page >= totalPages ? 'not-allowed' : 'pointer', fontSize: '14px', fontWeight: 500,
                    opacity: page >= totalPages ? 0.5 : 1,
                  }}
                >Older →</button>
              </div>
            )}
          </>
        )}

        {/* Newsletter CTA */}
        <div className="blog-newsletter-section">
          <div className="blog-newsletter-title">Get uptime tips in your inbox</div>
          <div className="blog-newsletter-sub">No spam. Guides, monitoring insights, and outage alerts for site owners.</div>
          <form className="blog-newsletter-form" onSubmit={e => e.preventDefault()}>
            <input className="blog-newsletter-input" type="email" placeholder="you@example.com" />
            <button type="submit" className="blog-newsletter-btn">Subscribe</button>
          </form>
        </div>
      </div>
    </div>
  )
}

export function BlogIndexClient({ posts }: { posts: UnifiedPost[] }) {
  return (
    <Suspense fallback={<div style={{ padding: '48px 0', textAlign: 'center', color: 'var(--text-muted)' }}>Loading posts…</div>}>
      <BlogIndexContent posts={posts} />
    </Suspense>
  )
}
