'use client'

import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { Suspense } from 'react'
import type { UnifiedPost } from './page'

const POSTS_PER_PAGE = 6

function BlogIndexContent({ posts }: { posts: UnifiedPost[] }) {
  const searchParams = useSearchParams()
  const router = useRouter()
  const page = Math.max(1, parseInt(searchParams.get('page') ?? '1', 10))

  const totalPages = Math.ceil(posts.length / POSTS_PER_PAGE)
  const start = (page - 1) * POSTS_PER_PAGE
  const pagePosts = posts.slice(start, start + POSTS_PER_PAGE)

  function goToPage(p: number) {
    const params = new URLSearchParams(searchParams.toString())
    if (p === 1) {
      params.delete('page')
    } else {
      params.set('page', String(p))
    }
    router.push(`/blog${params.size > 0 ? `?${params.toString()}` : ''}`)
  }

  return (
    <div className="blog-index">
      <div className="blog-index-header">
        <h1 className="blog-index-title">Uptrue Blog</h1>
        <p className="blog-index-subtitle">
          Guides, monitoring tips, outage reports, and uptime insights for developers, agencies, and site owners.
        </p>
      </div>

      <div className="blog-posts-grid">
        {pagePosts.map(post => (
          <Link key={post.slug} href={`/blog/${post.slug}`} className="blog-post-card">
            <div className="blog-post-card-body">
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <span className="blog-post-category">{post.category}</span>
                {post.isAutoGenerated && (
                  <span style={{
                    display: 'inline-block',
                    fontSize: '11px',
                    fontWeight: 600,
                    color: '#dc2626',
                    background: 'rgba(220, 38, 38, 0.08)',
                    padding: '2px 8px',
                    borderRadius: '20px',
                    textTransform: 'uppercase',
                    letterSpacing: '0.5px',
                  }}>
                    Live
                  </span>
                )}
              </div>
              <div className="blog-post-card-title">{post.title}</div>
              <div className="blog-post-card-excerpt">{post.excerpt}</div>
              <div className="blog-post-card-meta">
                <span>{post.displayDate}</span>
                <span className="blog-post-card-dot" />
                <span>{post.readTime}</span>
              </div>
            </div>
          </Link>
        ))}
      </div>

      {totalPages > 1 && (
        <div className="blog-pagination">
          <button
            onClick={() => goToPage(page - 1)}
            disabled={page <= 1}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '8px 16px',
              background: 'none',
              border: '1px solid var(--border-primary)',
              borderRadius: '8px',
              color: page <= 1 ? 'var(--text-muted)' : 'var(--text-primary)',
              cursor: page <= 1 ? 'not-allowed' : 'pointer',
              fontSize: '14px',
              fontWeight: 500,
              opacity: page <= 1 ? 0.5 : 1,
            }}
          >
            ← Newer Posts
          </button>

          <span className="blog-pagination-info">
            Page {page} of {totalPages} &nbsp;·&nbsp; {posts.length} posts
          </span>

          <button
            onClick={() => goToPage(page + 1)}
            disabled={page >= totalPages}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '8px 16px',
              background: 'none',
              border: '1px solid var(--border-primary)',
              borderRadius: '8px',
              color: page >= totalPages ? 'var(--text-muted)' : 'var(--text-primary)',
              cursor: page >= totalPages ? 'not-allowed' : 'pointer',
              fontSize: '14px',
              fontWeight: 500,
              opacity: page >= totalPages ? 0.5 : 1,
            }}
          >
            Older Posts →
          </button>
        </div>
      )}
    </div>
  )
}

export function BlogIndexClient({ posts }: { posts: UnifiedPost[] }) {
  return (
    <Suspense fallback={<div style={{ padding: '48px 0', textAlign: 'center', color: 'var(--text-muted)' }}>Loading posts…</div>}>
      <BlogIndexContent posts={posts} />
    </Suspense>
  )
}
