-- =============================================================================
-- Seed: content_calendar — 168-page content plan
-- Generated from keyword-research/Content_Calendar.csv
-- Total valid rows: 133 (skipped 35 — wiki + invalid)
-- Idempotent: uses ON CONFLICT (url_path) DO NOTHING.
-- Run AFTER migration 00085 has been applied.
-- =============================================================================

INSERT INTO content_calendar (
  publish_date, post_type, hub, primary_keyword, secondary_keywords,
  search_volume, kd, url_path, title_draft, author, brand_prefix_required
) VALUES
  ('2026-05-02', 'hub_foundational', 'http-uptime', 'website monitoring', ARRAY['is this site down', 'uptime monitoring', 'monitor a website']::text[], 0, 0, '/blog/http-uptime-monitoring-complete-guide', 'HTTP/Uptime Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'ssl', 'ssl monitoring', ARRAY['ssl certificate monitoring', 'ssl expiry monitoring', 'monitor ssl certificate expiration']::text[], 0, 0, '/blog/ssl-monitoring-complete-guide', 'SSL Certificate Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'dns', 'dns lookup', ARRAY['dns records', 'check dns records', 'dns test']::text[], 0, 0, '/blog/dns-monitoring-complete-guide', 'DNS Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'keyword', 'monitor website content changes', ARRAY['website content change monitor']::text[], 0, 0, '/blog/keyword-monitoring-complete-guide', 'Keyword Detection — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'domain', 'domain renewal tracker', ARRAY['track client domain expiration', 'domain expiration monitoring']::text[], 0, 0, '/blog/domain-monitoring-complete-guide', 'Domain Expiry Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'port', 'network port monitoring', ARRAY['port monitoring software', 'port monitoring tool']::text[], 0, 0, '/blog/port-monitoring-complete-guide', 'Port Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'ping', 'ping for website', ARRAY['ping test website', 'ping my site', 'web ping test']::text[], 0, 0, '/blog/ping-monitoring-complete-guide', 'Ping / Reachability — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'api', 'api monitoring tools', ARRAY['api uptime monitoring', 'api monitoring dashboard']::text[], 0, 0, '/blog/api-monitoring-complete-guide', 'API Endpoint Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'heartbeat', 'heartbeat monitoring', ARRAY['cron monitoring', 'cron job monitor']::text[], 0, 0, '/blog/heartbeat-monitoring-complete-guide', 'Heartbeat Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'competitor', 'monitor website for changes', ARRAY['website change monitor', 'monitor website changes']::text[], 0, 0, '/blog/competitor-monitoring-complete-guide', 'Page Change Detection — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'security-headers', 'security headers', ARRAY['csp header', 'hsts header', 'content security policy']::text[], 0, 0, '/blog/security-headers-monitoring-complete-guide', 'Security Headers Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'response-time', 'application performance monitoring tools', ARRAY['website performance monitoring', 'page speed and seo']::text[], 0, 0, '/blog/response-time-monitoring-complete-guide', 'Response Time Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'robots-txt', 'robots txt checker', ARRAY['robots.txt']::text[], 0, 0, '/blog/robots-txt-monitoring-complete-guide', 'robots.txt Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'ip-change', 'monitor ip address', ARRAY[]::text[], 0, 0, '/blog/ip-change-monitoring-complete-guide', 'IP Address Change Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'mx-health', 'mail server monitoring tools', ARRAY['mx record', 'email deliver']::text[], 0, 0, '/blog/mx-health-monitoring-complete-guide', 'MX / Mail Server Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'whois', 'whois lookup', ARRAY['registrar', 'domain owner']::text[], 0, 0, '/blog/whois-monitoring-complete-guide', 'WHOIS Registrar Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'sitemap', 'sitemap', ARRAY['xml sitemap']::text[], 0, 0, '/blog/sitemap-monitoring-complete-guide', 'Sitemap Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'redirect-chain', 'redirect chain', ARRAY['redirect loop', '301 redirect', 'redirect check']::text[], 0, 0, '/blog/redirect-chain-monitoring-complete-guide', 'Redirect Chain Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'spf-dmarc', 'spf', ARRAY['dmarc', 'dkim', 'free dmarc monitoring']::text[], 0, 0, '/blog/spf-dmarc-monitoring-complete-guide', 'SPF/DMARC Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-02', 'hub_foundational', 'blacklist', 'blacklist', ARRAY['spamhaus', 'dnsbl', 'rbl']::text[], 0, 0, '/blog/blacklist-monitoring-complete-guide', 'Blacklist Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-03', 'hub_foundational', 'page-size', 'page size', ARRAY['page weight']::text[], 0, 0, '/blog/page-size-monitoring-complete-guide', 'Page Size Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-03', 'hub_foundational', 'cookie-consent', 'cookie consent', ARRAY['cookie banner', 'gdpr cookie banner']::text[], 0, 0, '/blog/cookie-consent-monitoring-complete-guide', 'Cookie Consent Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-03', 'hub_foundational', 'nameserver', 'name server', ARRAY['nameserver', 'ns record']::text[], 0, 0, '/blog/nameserver-monitoring-complete-guide', 'Nameserver Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-03', 'hub_foundational', 'wordpress', 'wordpress monitoring', ARRAY['wordpress security monitoring', 'wordpress site monitoring', 'wordpress uptime monitoring']::text[], 0, 0, '/blog/wordpress-monitoring-complete-guide', 'WordPress Site Monitoring — The Complete Guide for 2026', 'Steve', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', 'website not loading', ARRAY[]::text[], 0, 0, '/blog/website-not-loading', 'How to Fix: Website Not Loading', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', '503 service unavailable error', ARRAY[]::text[], 0, 0, '/blog/503-service-unavailable-error', 'How to Fix: 503 Service Unavailable Error', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', '504 gateway timeout', ARRAY[]::text[], 0, 0, '/blog/504-gateway-timeout', 'How to Fix: 504 Gateway Timeout', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', '502 bad gateway', ARRAY[]::text[], 0, 0, '/blog/502-bad-gateway', 'How to Fix: 502 Bad Gateway', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', 'connection timeout error', ARRAY[]::text[], 0, 0, '/blog/connection-timeout-error', 'How to Fix: Connection Timeout Error', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', 'site keeps going down', ARRAY[]::text[], 0, 0, '/blog/site-keeps-going-down', 'How to Fix: Site Keeps Going Down', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'http-uptime', 'why is my website slow to load', ARRAY[]::text[], 0, 0, '/blog/why-is-my-website-slow-to-load', 'How to Fix: Why Is My Website Slow To Load', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'ssl certificate expired error', ARRAY[]::text[], 0, 0, '/blog/ssl-certificate-expired-error', 'How to Fix: Ssl Certificate Expired Error', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'ssl certificate not trusted', ARRAY[]::text[], 0, 0, '/blog/ssl-certificate-not-trusted', 'How to Fix: Ssl Certificate Not Trusted', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'ssl handshake failed', ARRAY[]::text[], 0, 0, '/blog/ssl-handshake-failed', 'How to Fix: Ssl Handshake Failed', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'mixed content warning', ARRAY[]::text[], 0, 0, '/blog/mixed-content-warning', 'How to Fix: Mixed Content Warning', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'connection not secure error', ARRAY[]::text[], 0, 0, '/blog/connection-not-secure-error', 'How to Fix: Connection Not Secure Error', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'how to renew lets encrypt certificate', ARRAY[]::text[], 0, 0, '/blog/how-to-renew-lets-encrypt-certificate', 'How to Fix: How To Renew Lets Encrypt Certificate', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'ssl', 'fix err_cert_authority_invalid', ARRAY[]::text[], 0, 0, '/blog/fix-err-cert-authority-invalid', 'How to Fix: Fix Err_Cert_Authority_Invalid', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'dns', 'dns_probe_finished_nxdomain fix', ARRAY[]::text[], 0, 0, '/blog/dns-probe-finished-nxdomain-fix', 'How to Fix: Dns_Probe_Finished_Nxdomain Fix', 'Aradhna', false),
  ('2026-05-03', 'troubleshooting', 'dns', 'dns server not responding', ARRAY[]::text[], 0, 0, '/blog/dns-server-not-responding', 'How to Fix: Dns Server Not Responding', 'Aradhna', false),
  ('2026-05-04', 'troubleshooting', 'dns', 'how to flush dns cache', ARRAY[]::text[], 0, 0, '/blog/how-to-flush-dns-cache', 'How to Fix: How To Flush Dns Cache', 'Aradhna', false),
  ('2026-05-04', 'troubleshooting', 'dns', 'dns propagation taking too long', ARRAY[]::text[], 0, 0, '/blog/dns-propagation-taking-too-long', 'How to Fix: Dns Propagation Taking Too Long', 'Aradhna', false),
  ('2026-05-04', 'troubleshooting', 'dns', 'fix dns resolution error', ARRAY[]::text[], 0, 0, '/blog/fix-dns-resolution-error', 'How to Fix: Fix Dns Resolution Error', 'Aradhna', false),
  ('2026-05-05', 'troubleshooting', 'keyword', 'why is my product description disappearing', ARRAY[]::text[], 0, 0, '/blog/why-is-my-product-description-disappearing', 'How to Fix: Why Is My Product Description Disappearing', 'Aradhna', false),
  ('2026-05-05', 'troubleshooting', 'keyword', 'page content changed without my approval', ARRAY[]::text[], 0, 0, '/blog/page-content-changed-without-my-approval', 'How to Fix: Page Content Changed Without My Approval', 'Aradhna', false),
  ('2026-05-05', 'troubleshooting', 'domain', 'domain expired what to do', ARRAY[]::text[], 0, 0, '/blog/domain-expired-what-to-do', 'How to Fix: Domain Expired What To Do', 'Aradhna', false),
  ('2026-05-06', 'troubleshooting', 'domain', 'how to recover an expired domain', ARRAY[]::text[], 0, 0, '/blog/how-to-recover-an-expired-domain', 'How to Fix: How To Recover An Expired Domain', 'Aradhna', false),
  ('2026-05-06', 'troubleshooting', 'domain', 'domain auto renew failed', ARRAY[]::text[], 0, 0, '/blog/domain-auto-renew-failed', 'How to Fix: Domain Auto Renew Failed', 'Aradhna', false),
  ('2026-05-06', 'troubleshooting', 'port', 'port 443 not responding', ARRAY[]::text[], 0, 0, '/blog/port-443-not-responding', 'How to Fix: Port 443 Not Responding', 'Aradhna', false),
  ('2026-05-07', 'troubleshooting', 'port', 'port 80 closed', ARRAY[]::text[], 0, 0, '/blog/port-80-closed', 'How to Fix: Port 80 Closed', 'Aradhna', false),
  ('2026-05-07', 'troubleshooting', 'port', 'firewall blocking port', ARRAY[]::text[], 0, 0, '/blog/firewall-blocking-port', 'How to Fix: Firewall Blocking Port', 'Aradhna', false),
  ('2026-05-07', 'troubleshooting', 'ping', '100 percent packet loss', ARRAY[]::text[], 0, 0, '/blog/100-percent-packet-loss', 'How to Fix: 100 Percent Packet Loss', 'Aradhna', false),
  ('2026-05-08', 'troubleshooting', 'ping', 'request timed out ping', ARRAY[]::text[], 0, 0, '/blog/request-timed-out-ping', 'How to Fix: Request Timed Out Ping', 'Aradhna', false),
  ('2026-05-08', 'troubleshooting', 'ping', 'high ping latency', ARRAY[]::text[], 0, 0, '/blog/high-ping-latency', 'How to Fix: High Ping Latency', 'Aradhna', false),
  ('2026-05-08', 'troubleshooting', 'api', 'rest api 401 unauthorized', ARRAY[]::text[], 0, 0, '/blog/rest-api-401-unauthorized', 'How to Fix: Rest Api 401 Unauthorized', 'Aradhna', false),
  ('2026-05-09', 'troubleshooting', 'api', 'api rate limit exceeded', ARRAY[]::text[], 0, 0, '/blog/api-rate-limit-exceeded', 'How to Fix: Api Rate Limit Exceeded', 'Aradhna', false),
  ('2026-05-09', 'troubleshooting', 'api', 'api endpoint timeout', ARRAY[]::text[], 0, 0, '/blog/api-endpoint-timeout', 'How to Fix: Api Endpoint Timeout', 'Aradhna', false),
  ('2026-05-09', 'troubleshooting', 'api', 'graphql endpoint down', ARRAY[]::text[], 0, 0, '/blog/graphql-endpoint-down', 'How to Fix: Graphql Endpoint Down', 'Aradhna', false),
  ('2026-05-10', 'troubleshooting', 'heartbeat', 'cron job not running', ARRAY[]::text[], 0, 0, '/blog/cron-job-not-running', 'How to Fix: Cron Job Not Running', 'Aradhna', false),
  ('2026-05-10', 'troubleshooting', 'heartbeat', 'why did my backup fail silently', ARRAY[]::text[], 0, 0, '/blog/why-did-my-backup-fail-silently', 'How to Fix: Why Did My Backup Fail Silently', 'Aradhna', false),
  ('2026-05-10', 'troubleshooting', 'heartbeat', 'how to detect cron failure', ARRAY[]::text[], 0, 0, '/blog/how-to-detect-cron-failure', 'How to Fix: How To Detect Cron Failure', 'Aradhna', false),
  ('2026-05-11', 'troubleshooting', 'competitor', 'my pricing page was edited without me', ARRAY[]::text[], 0, 0, '/blog/my-pricing-page-was-edited-without-me', 'How to Fix: My Pricing Page Was Edited Without Me', 'Aradhna', false),
  ('2026-05-11', 'troubleshooting', 'competitor', 'how to detect competitor price change', ARRAY[]::text[], 0, 0, '/blog/how-to-detect-competitor-price-change', 'How to Fix: How To Detect Competitor Price Change', 'Aradhna', false),
  ('2026-05-11', 'troubleshooting', 'security-headers', 'x-frame-options not set', ARRAY[]::text[], 0, 0, '/blog/x-frame-options-not-set', 'How to Fix: X-Frame-Options Not Set', 'Aradhna', false),
  ('2026-05-12', 'troubleshooting', 'security-headers', 'csp violation errors', ARRAY[]::text[], 0, 0, '/blog/csp-violation-errors', 'How to Fix: Csp Violation Errors', 'Aradhna', false),
  ('2026-05-12', 'troubleshooting', 'security-headers', 'how to add hsts to nginx', ARRAY[]::text[], 0, 0, '/blog/how-to-add-hsts-to-nginx', 'How to Fix: How To Add Hsts To Nginx', 'Aradhna', false),
  ('2026-05-12', 'troubleshooting', 'security-headers', 'fix missing security headers', ARRAY[]::text[], 0, 0, '/blog/fix-missing-security-headers', 'How to Fix: Fix Missing Security Headers', 'Aradhna', false),
  ('2026-05-13', 'troubleshooting', 'response-time', 'why is my website so slow', ARRAY[]::text[], 0, 0, '/blog/why-is-my-website-so-slow', 'How to Fix: Why Is My Website So Slow', 'Aradhna', false),
  ('2026-05-13', 'troubleshooting', 'response-time', 'core web vitals failing', ARRAY[]::text[], 0, 0, '/blog/core-web-vitals-failing', 'How to Fix: Core Web Vitals Failing', 'Aradhna', false),
  ('2026-05-13', 'troubleshooting', 'response-time', 'ttfb too high', ARRAY[]::text[], 0, 0, '/blog/ttfb-too-high', 'How to Fix: Ttfb Too High', 'Aradhna', false),
  ('2026-05-14', 'troubleshooting', 'response-time', 'lcp over 4 seconds', ARRAY[]::text[], 0, 0, '/blog/lcp-over-4-seconds', 'How to Fix: Lcp Over 4 Seconds', 'Aradhna', false),
  ('2026-05-14', 'troubleshooting', 'robots-txt', 'my site disappeared from google after deploy', ARRAY[]::text[], 0, 0, '/blog/my-site-disappeared-from-google-after-deploy', 'How to Fix: My Site Disappeared From Google After Deploy', 'Aradhna', false),
  ('2026-05-14', 'troubleshooting', 'robots-txt', 'accidentally blocked googlebot', ARRAY[]::text[], 0, 0, '/blog/accidentally-blocked-googlebot', 'How to Fix: Accidentally Blocked Googlebot', 'Aradhna', false),
  ('2026-05-15', 'troubleshooting', 'robots-txt', 'how to fix disallow all in robots txt', ARRAY[]::text[], 0, 0, '/blog/how-to-fix-disallow-all-in-robots-txt', 'How to Fix: How To Fix Disallow All In Robots Txt', 'Aradhna', false),
  ('2026-05-15', 'informational', 'http-uptime', 'what is uptime monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-uptime-monitoring', 'What Is Uptime Monitoring', 'Krithi', false),
  ('2026-05-15', 'informational', 'http-uptime', 'how does uptime monitoring work', ARRAY[]::text[], 0, 0, '/blog/how-does-uptime-monitoring-work', 'How Does Uptime Monitoring Work', 'Krithi', false),
  ('2026-05-16', 'informational', 'http-uptime', 'uptime sla explained', ARRAY[]::text[], 0, 0, '/blog/uptime-sla-explained', 'Uptime Sla Explained', 'Krithi', false),
  ('2026-05-16', 'informational', 'http-uptime', 'difference between uptime and availability', ARRAY[]::text[], 0, 0, '/blog/difference-between-uptime-and-availability', 'Difference Between Uptime And Availability', 'Krithi', false),
  ('2026-05-16', 'informational', 'ssl', 'what is an ssl certificate', ARRAY[]::text[], 0, 0, '/blog/what-is-an-ssl-certificate', 'What Is An Ssl Certificate', 'Krithi', false),
  ('2026-05-17', 'informational', 'ssl', 'how does ssl work', ARRAY[]::text[], 0, 0, '/blog/how-does-ssl-work', 'How Does Ssl Work', 'Krithi', false),
  ('2026-05-17', 'informational', 'ssl', 'ssl vs tls explained', ARRAY[]::text[], 0, 0, '/blog/ssl-vs-tls-explained', 'Ssl Vs Tls Explained', 'Krithi', false),
  ('2026-05-17', 'informational', 'ssl', 'wildcard ssl certificate explained', ARRAY[]::text[], 0, 0, '/blog/wildcard-ssl-certificate-explained', 'Wildcard Ssl Certificate Explained', 'Krithi', false),
  ('2026-05-18', 'informational', 'dns', 'what is dns', ARRAY[]::text[], 0, 0, '/blog/what-is-dns', 'What Is Dns', 'Krithi', false),
  ('2026-05-18', 'informational', 'dns', 'dns record types explained', ARRAY[]::text[], 0, 0, '/blog/dns-record-types-explained', 'Dns Record Types Explained', 'Krithi', false),
  ('2026-05-18', 'informational', 'dns', 'how dns works', ARRAY[]::text[], 0, 0, '/blog/how-dns-works', 'How Dns Works', 'Krithi', false),
  ('2026-05-19', 'informational', 'dns', 'a record vs cname record', ARRAY[]::text[], 0, 0, '/blog/a-record-vs-cname-record', 'A Record Vs Cname Record', 'Krithi', false),
  ('2026-05-19', 'informational', 'keyword', 'what is content change monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-content-change-monitoring', 'What Is Content Change Monitoring', 'Krithi', false),
  ('2026-05-19', 'informational', 'keyword', 'how to monitor website content for changes', ARRAY[]::text[], 0, 0, '/blog/how-to-monitor-website-content-for-changes', 'How To Monitor Website Content For Changes', 'Krithi', false),
  ('2026-05-20', 'informational', 'domain', 'what is domain expiry', ARRAY[]::text[], 0, 0, '/blog/what-is-domain-expiry', 'What Is Domain Expiry', 'Krithi', false),
  ('2026-05-20', 'informational', 'domain', 'how to never lose a domain', ARRAY[]::text[], 0, 0, '/blog/how-to-never-lose-a-domain', 'How To Never Lose A Domain', 'Krithi', false),
  ('2026-05-20', 'informational', 'domain', 'domain expiry vs hosting expiry', ARRAY[]::text[], 0, 0, '/blog/domain-expiry-vs-hosting-expiry', 'Domain Expiry Vs Hosting Expiry', 'Krithi', false),
  ('2026-05-21', 'informational', 'port', 'what is a port check', ARRAY[]::text[], 0, 0, '/blog/what-is-a-port-check', 'What Is A Port Check', 'Krithi', false),
  ('2026-05-21', 'informational', 'port', 'tcp vs udp port monitoring', ARRAY[]::text[], 0, 0, '/blog/tcp-vs-udp-port-monitoring', 'Tcp Vs Udp Port Monitoring', 'Krithi', false),
  ('2026-05-21', 'informational', 'ping', 'what is ping monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-ping-monitoring', 'What Is Ping Monitoring', 'Krithi', false),
  ('2026-05-22', 'informational', 'ping', 'icmp vs tcp ping', ARRAY[]::text[], 0, 0, '/blog/icmp-vs-tcp-ping', 'Icmp Vs Tcp Ping', 'Krithi', false),
  ('2026-05-22', 'informational', 'api', 'what is api monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-api-monitoring', 'What Is Api Monitoring', 'Krithi', false),
  ('2026-05-22', 'informational', 'api', 'rest vs graphql monitoring', ARRAY[]::text[], 0, 0, '/blog/rest-vs-graphql-monitoring', 'Rest Vs Graphql Monitoring', 'Krithi', false),
  ('2026-05-23', 'informational', 'api', 'api sla best practices', ARRAY[]::text[], 0, 0, '/blog/api-sla-best-practices', 'Api Sla Best Practices', 'Krithi', false),
  ('2026-05-23', 'informational', 'heartbeat', 'what is heartbeat monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-heartbeat-monitoring', 'What Is Heartbeat Monitoring', 'Krithi', false),
  ('2026-05-23', 'informational', 'heartbeat', 'dead mans switch explained', ARRAY[]::text[], 0, 0, '/blog/dead-mans-switch-explained', 'Dead Mans Switch Explained', 'Krithi', false),
  ('2026-05-24', 'informational', 'heartbeat', 'cron monitoring vs uptime', ARRAY[]::text[], 0, 0, '/blog/cron-monitoring-vs-uptime', 'Cron Monitoring Vs Uptime', 'Krithi', false),
  ('2026-05-24', 'informational', 'competitor', 'what is page change monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-page-change-monitoring', 'What Is Page Change Monitoring', 'Krithi', false),
  ('2026-05-24', 'informational', 'competitor', 'how to track competitor websites', ARRAY[]::text[], 0, 0, '/blog/how-to-track-competitor-websites', 'How To Track Competitor Websites', 'Krithi', false),
  ('2026-05-25', 'informational', 'competitor', 'best tools to watch website changes', ARRAY[]::text[], 0, 0, '/blog/best-tools-to-watch-website-changes', 'Best Tools To Watch Website Changes', 'Krithi', false),
  ('2026-05-25', 'informational', 'security-headers', 'what are http security headers', ARRAY[]::text[], 0, 0, '/blog/what-are-http-security-headers', 'What Are Http Security Headers', 'Krithi', false),
  ('2026-05-25', 'informational', 'security-headers', 'csp explained', ARRAY[]::text[], 0, 0, '/blog/csp-explained', 'Csp Explained', 'Krithi', false),
  ('2026-05-26', 'informational', 'security-headers', 'hsts vs https', ARRAY[]::text[], 0, 0, '/blog/hsts-vs-https', 'Hsts Vs Https', 'Krithi', false),
  ('2026-05-26', 'informational', 'response-time', 'what is response time monitoring', ARRAY[]::text[], 0, 0, '/blog/what-is-response-time-monitoring', 'What Is Response Time Monitoring', 'Krithi', false),
  ('2026-05-26', 'informational', 'response-time', 'core web vitals explained', ARRAY[]::text[], 0, 0, '/blog/core-web-vitals-explained', 'Core Web Vitals Explained', 'Krithi', false),
  ('2026-05-27', 'informational', 'response-time', 'rum vs synthetic monitoring', ARRAY[]::text[], 0, 0, '/blog/rum-vs-synthetic-monitoring', 'Rum Vs Synthetic Monitoring', 'Krithi', false),
  ('2026-05-27', 'combined_intent', 'tools-umbrella', 'website checker', ARRAY[]::text[], 22200, 60, '/tools/website-checker', 'Website Checker — All-in-One Health Test', 'Aradhna', false),
  ('2026-05-27', 'combined_intent', 'tools-umbrella', 'url checker', ARRAY[]::text[], 12100, 60, '/tools/url-checker', 'URL Checker — Status, Redirects, SSL & Safety', 'Aradhna', false),
  ('2026-05-28', 'combined_intent', 'tools-umbrella', 'site checker', ARRAY[]::text[], 9900, 60, '/tools/site-checker', 'Site Checker — Free Website Diagnostics', 'Aradhna', false),
  ('2026-05-28', 'combined_intent', 'tools-umbrella', 'domain checker', ARRAY[]::text[], 8100, 60, '/tools/domain-checker', 'Domain Checker — WHOIS, DNS, Expiry & Health', 'Aradhna', false),
  ('2026-05-28', 'combined_intent', 'tools-umbrella', 'seo checker', ARRAY[]::text[], 6600, 60, '/tools/seo-checker', 'SEO Checker — Free On-Page & Technical Audit', 'Aradhna', false),
  ('2026-05-29', 'combined_intent', 'tools-umbrella', 'safety checker', ARRAY[]::text[], 5400, 60, '/tools/safety-checker', 'Website Safety Checker — Free Trust Score', 'Aradhna', false),
  ('2026-05-29', 'combined_intent', 'tools-umbrella', 'scam website checker', ARRAY[]::text[], 5400, 60, '/tools/scam-website-checker', 'Scam Website Checker — Verify Site Safety', 'Aradhna', false),
  ('2026-05-29', 'commercial', 'http-uptime', 'uptrue vs uptimerobot', ARRAY[]::text[], 0, 0, '/blog/uptrue-vs-uptimerobot', 'Uptrue vs UptimeRobot', 'Sachin', false),
  ('2026-05-30', 'commercial', 'http-uptime', 'uptrue vs pingdom', ARRAY[]::text[], 0, 0, '/blog/uptrue-vs-pingdom', 'Uptrue vs Pingdom', 'Sachin', false),
  ('2026-05-30', 'commercial', 'http-uptime', 'uptrue vs betterstack (better uptime)', ARRAY[]::text[], 0, 0, '/blog/uptrue-vs-betterstack-better-uptime', 'Uptrue vs BetterStack (Better Uptime)', 'Sachin', false),
  ('2026-05-30', 'commercial', 'http-uptime', 'uptrue vs statuscake', ARRAY[]::text[], 0, 0, '/blog/uptrue-vs-statuscake', 'Uptrue vs Statuscake', 'Sachin', false),
  ('2026-05-31', 'commercial', 'http-uptime', 'uptrue vs site24x7', ARRAY[]::text[], 0, 0, '/blog/uptrue-vs-site24x7', 'Uptrue vs Site24x7', 'Sachin', false),
  ('2026-05-31', 'commercial', 'http-uptime', 'best uptime monitoring tools 2026', ARRAY[]::text[], 0, 0, '/blog/best-uptime-monitoring-tools-2026', 'Best uptime monitoring tools 2026', 'Sachin', false),
  ('2026-05-31', 'commercial', 'ssl', 'best ssl certificate monitoring tools 2026', ARRAY[]::text[], 0, 0, '/blog/best-ssl-certificate-monitoring-tools-2026', 'Best SSL certificate monitoring tools 2026', 'Sachin', false),
  ('2026-06-01', 'commercial', 'dns', 'best dns monitoring tools 2026', ARRAY[]::text[], 0, 0, '/blog/best-dns-monitoring-tools-2026', 'Best DNS monitoring tools 2026', 'Sachin', false),
  ('2026-06-01', 'commercial', 'api', 'best api monitoring tools 2026', ARRAY[]::text[], 0, 0, '/blog/best-api-monitoring-tools-2026', 'Best API monitoring tools 2026', 'Sachin', false),
  ('2026-06-01', 'commercial', 'wordpress', 'best wordpress security plugins 2026', ARRAY[]::text[], 0, 0, '/blog/best-wordpress-security-plugins-2026', 'Best WordPress security plugins 2026', 'Sachin', false),
  ('2026-06-02', 'commercial', 'http-uptime', 'best free website monitoring tools', ARRAY[]::text[], 0, 0, '/blog/best-free-website-monitoring-tools', 'Best free website monitoring tools', 'Sachin', false),
  ('2026-06-02', 'commercial', 'http-uptime', 'best status page providers 2026', ARRAY[]::text[], 0, 0, '/blog/best-status-page-providers-2026', 'Best status page providers 2026', 'Sachin', false),
  ('2026-06-02', 'commercial', 'http-uptime', 'uptimerobot alternatives 2026', ARRAY[]::text[], 0, 0, '/blog/uptimerobot-alternatives-2026', 'UptimeRobot alternatives 2026', 'Sachin', false),
  ('2026-06-03', 'commercial', 'http-uptime', 'pingdom alternatives 2026', ARRAY[]::text[], 0, 0, '/blog/pingdom-alternatives-2026', 'Pingdom alternatives 2026', 'Sachin', false),
  ('2026-06-03', 'commercial', 'blacklist', 'best blacklist monitoring services', ARRAY[]::text[], 0, 0, '/blog/best-blacklist-monitoring-services', 'Best blacklist monitoring services', 'Sachin', false),
  ('2026-06-03', 'commercial', 'spf-dmarc', 'best dmarc monitoring services free and paid', ARRAY[]::text[], 0, 0, '/blog/best-dmarc-monitoring-services-free-and-paid', 'Best DMARC monitoring services free and paid', 'Sachin', false)
ON CONFLICT (url_path) DO NOTHING;

-- Verify:
--   SELECT post_type, count(*) FROM content_calendar GROUP BY post_type ORDER BY count(*) DESC;
--   SELECT count(*) FROM content_calendar;  -- should equal 133