-- Public Tracker — Batch 4 (278 sites → total ~500)
-- ON CONFLICT DO NOTHING prevents duplicates

INSERT INTO public_monitors (domain, display_name, category, is_active) VALUES

  -- AI (13)
  ('cohere.com',            'Cohere',           'AI',                   true),
  ('mistral.ai',            'Mistral AI',        'AI',                   true),
  ('elevenlabs.io',         'ElevenLabs',        'AI',                   true),
  ('runwayml.com',          'Runway',            'AI',                   true),
  ('jasper.ai',             'Jasper',            'AI',                   true),
  ('copy.ai',               'Copy.ai',           'AI',                   true),
  ('writesonic.com',        'Writesonic',        'AI',                   true),
  ('character.ai',          'Character.AI',      'AI',                   true),
  ('groq.com',              'Groq',              'AI',                   true),
  ('together.ai',           'Together AI',       'AI',                   true),
  ('deepmind.google',       'DeepMind',          'AI',                   true),
  ('grok.com',              'Grok',              'AI',                   true),
  ('civitai.com',           'Civitai',           'AI',                   true),

  -- Cloud & Hosting (13)
  ('siteground.com',        'SiteGround',        'Cloud & Hosting',      true),
  ('kinsta.com',            'Kinsta',            'Cloud & Hosting',      true),
  ('wpengine.com',          'WP Engine',         'Cloud & Hosting',      true),
  ('cloudways.com',         'Cloudways',         'Cloud & Hosting',      true),
  ('hostinger.com',         'Hostinger',         'Cloud & Hosting',      true),
  ('dreamhost.com',         'DreamHost',         'Cloud & Hosting',      true),
  ('namecheap.com',         'Namecheap',         'Cloud & Hosting',      true),
  ('rackspace.com',         'Rackspace',         'Cloud & Hosting',      true),
  ('a2hosting.com',         'A2 Hosting',        'Cloud & Hosting',      true),
  ('liquidweb.com',         'Liquid Web',        'Cloud & Hosting',      true),
  ('pantheon.io',           'Pantheon',          'Cloud & Hosting',      true),
  ('platform.sh',           'Platform.sh',       'Cloud & Hosting',      true),
  ('stormwind.io',          'Stormwind',         'Cloud & Hosting',      true),

  -- Dev Tools (18)
  ('grafana.com',           'Grafana',           'Dev Tools',            true),
  ('elastic.co',            'Elastic',           'Dev Tools',            true),
  ('circleci.com',          'CircleCI',          'Dev Tools',            true),
  ('jenkins.io',            'Jenkins',           'Dev Tools',            true),
  ('sonarcloud.io',         'SonarCloud',        'Dev Tools',            true),
  ('kubernetes.io',         'Kubernetes',        'Dev Tools',            true),
  ('terraform.io',          'Terraform',         'Dev Tools',            true),
  ('atlassian.com',         'Atlassian',         'Dev Tools',            true),
  ('nuget.org',             'NuGet',             'Dev Tools',            true),
  ('rubygems.org',          'RubyGems',          'Dev Tools',            true),
  ('packagist.org',         'Packagist',         'Dev Tools',            true),
  ('hex.pm',                'Hex',               'Dev Tools',            true),
  ('hub.docker.com',        'Docker Hub',        'Dev Tools',            true),
  ('vercel.com',            'Vercel',            'Dev Tools',            true),
  ('cloudflare.dev',        'Cloudflare Workers','Dev Tools',            true),
  ('readme.com',            'ReadMe',            'Dev Tools',            true),
  ('swagger.io',            'Swagger',           'Dev Tools',            true),
  ('insomnia.rest',         'Insomnia',          'Dev Tools',            true),

  -- E-commerce (16)
  ('zalando.com',           'Zalando',           'E-commerce',           true),
  ('depop.com',             'Depop',             'E-commerce',           true),
  ('vinted.com',            'Vinted',            'E-commerce',           true),
  ('poshmark.com',          'Poshmark',          'E-commerce',           true),
  ('boohoo.com',            'Boohoo',            'E-commerce',           true),
  ('prettylittlething.com', 'PrettyLittleThing', 'E-commerce',           true),
  ('argos.co.uk',           'Argos',             'E-commerce',           true),
  ('currys.co.uk',          'Currys',            'E-commerce',           true),
  ('farfetch.com',          'Farfetch',          'E-commerce',           true),
  ('noon.com',              'Noon',              'E-commerce',           true),
  ('shopee.com',            'Shopee',            'E-commerce',           true),
  ('lazada.com',            'Lazada',            'E-commerce',           true),
  ('mercadolibre.com',      'MercadoLibre',      'E-commerce',           true),
  ('jd.com',                'JD.com',            'E-commerce',           true),
  ('taobao.com',            'Taobao',            'E-commerce',           true),
  ('overstock.com',         'Overstock',         'E-commerce',           true),

  -- Finance (18)
  ('chase.com',             'Chase',             'Finance',              true),
  ('barclays.co.uk',        'Barclays',          'Finance',              true),
  ('hsbc.com',              'HSBC',              'Finance',              true),
  ('lloydsbank.com',        'Lloyds Bank',       'Finance',              true),
  ('santander.com',         'Santander',         'Finance',              true),
  ('natwest.com',           'NatWest',           'Finance',              true),
  ('capitalone.com',        'Capital One',       'Finance',              true),
  ('sofi.com',              'SoFi',              'Finance',              true),
  ('chime.com',             'Chime',             'Finance',              true),
  ('starlingbank.com',      'Starling Bank',     'Finance',              true),
  ('freetrade.io',          'Freetrade',         'Finance',              true),
  ('fidelity.com',          'Fidelity',          'Finance',              true),
  ('schwab.com',            'Charles Schwab',    'Finance',              true),
  ('vanguard.com',          'Vanguard',          'Finance',              true),
  ('payoneer.com',          'Payoneer',          'Finance',              true),
  ('moneybox.com',          'Moneybox',          'Finance',              true),
  ('nutmeg.com',            'Nutmeg',            'Finance',              true),
  ('ig.com',                'IG',                'Finance',              true),

  -- Education (10)
  ('brilliant.org',         'Brilliant',         'Education',            true),
  ('masterclass.com',       'MasterClass',       'Education',            true),
  ('futurelearn.com',       'FutureLearn',       'Education',            true),
  ('open.ac.uk',            'The Open University','Education',           true),
  ('chegg.com',             'Chegg',             'Education',            true),
  ('quizlet.com',           'Quizlet',           'Education',            true),
  ('academia.edu',          'Academia.edu',      'Education',            true),
  ('ted.com',               'TED',               'Education',            true),
  ('w3schools.com',         'W3Schools',         'Education',            true),
  ('mdn.web.docs',          'MDN Web Docs',      'Education',            true),

  -- Gaming (12)
  ('nintendo.com',          'Nintendo',          'Gaming',               true),
  ('ubisoft.com',           'Ubisoft',           'Gaming',               true),
  ('activision.com',        'Activision',        'Gaming',               true),
  ('blizzard.com',          'Blizzard',          'Gaming',               true),
  ('riotgames.com',         'Riot Games',        'Gaming',               true),
  ('minecraft.net',         'Minecraft',         'Gaming',               true),
  ('itch.io',               'itch.io',           'Gaming',               true),
  ('gog.com',               'GOG',               'Gaming',               true),
  ('humblebundle.com',      'Humble Bundle',     'Gaming',               true),
  ('g2a.com',               'G2A',               'Gaming',               true),
  ('leagueoflegends.com',   'League of Legends', 'Gaming',               true),
  ('valorant.com',          'Valorant',          'Gaming',               true),

  -- Healthcare (8)
  ('bupa.co.uk',            'Bupa',              'Healthcare',           true),
  ('mayoclinic.org',        'Mayo Clinic',       'Healthcare',           true),
  ('nih.gov',               'NIH',               'Healthcare',           true),
  ('who.int',               'WHO',               'Healthcare',           true),
  ('drugs.com',             'Drugs.com',         'Healthcare',           true),
  ('patient.info',          'Patient.info',      'Healthcare',           true),
  ('nhs.uk',                'NHS',               'Healthcare',           true),
  ('medicinenet.com',       'MedicineNet',       'Healthcare',           true),

  -- Business & CRM (12)
  ('salesforce.com',        'Salesforce',        'Business',             true),
  ('pipedrive.com',         'Pipedrive',         'Business',             true),
  ('freshworks.com',        'Freshworks',        'Business',             true),
  ('zoho.com',              'Zoho',              'Business',             true),
  ('xero.com',              'Xero',              'Business',             true),
  ('quickbooks.intuit.com', 'QuickBooks',        'Business',             true),
  ('sage.com',              'Sage',              'Business',             true),
  ('servicenow.com',        'ServiceNow',        'Business',             true),
  ('sap.com',               'SAP',               'Business',             true),
  ('oracle.com',            'Oracle',            'Business',             true),
  ('docusign.com',          'DocuSign',          'Business',             true),
  ('legalzoom.com',         'LegalZoom',         'Business',             true),

  -- News & Media (14)
  ('forbes.com',            'Forbes',            'News & Media',         true),
  ('bloomberg.com',         'Bloomberg',         'News & Media',         true),
  ('ft.com',                'Financial Times',   'News & Media',         true),
  ('economist.com',         'The Economist',     'News & Media',         true),
  ('wired.com',             'Wired',             'News & Media',         true),
  ('techcrunch.com',        'TechCrunch',        'News & Media',         true),
  ('theverge.com',          'The Verge',         'News & Media',         true),
  ('arstechnica.com',       'Ars Technica',      'News & Media',         true),
  ('mashable.com',          'Mashable',          'News & Media',         true),
  ('engadget.com',          'Engadget',          'News & Media',         true),
  ('bbc.co.uk',             'BBC',               'News & Media',         true),
  ('apnews.com',            'AP News',           'News & Media',         true),
  ('aljazeera.com',         'Al Jazeera',        'News & Media',         true),
  ('independent.co.uk',     'The Independent',   'News & Media',         true),

  -- Music (5)
  ('tidal.com',             'Tidal',             'Music',                true),
  ('bandcamp.com',          'Bandcamp',          'Music',                true),
  ('last.fm',               'Last.fm',           'Music',                true),
  ('audiomack.com',         'Audiomack',         'Music',                true),
  ('mixcloud.com',          'Mixcloud',          'Music',                true),

  -- Productivity (10)
  ('dropbox.com',           'Dropbox',           'Productivity',         true),
  ('box.com',               'Box',               'Productivity',         true),
  ('drive.google.com',      'Google Drive',      'Productivity',         true),
  ('obsidian.md',           'Obsidian',          'Productivity',         true),
  ('coda.io',               'Coda',              'Productivity',         true),
  ('nuclino.com',           'Nuclino',           'Productivity',         true),
  ('craft.do',              'Craft',             'Productivity',         true),
  ('linear.app',            'Linear',            'Productivity',         true),
  ('height.app',            'Height',            'Productivity',         true),
  ('fibery.io',             'Fibery',            'Productivity',         true),

  -- Streaming & Video (10)
  ('peacocktv.com',         'Peacock',           'Streaming & Video',    true),
  ('paramountplus.com',     'Paramount+',        'Streaming & Video',    true),
  ('discoveryplus.com',     'Discovery+',        'Streaming & Video',    true),
  ('channel4.com',          'Channel 4',         'Streaming & Video',    true),
  ('itvx.com',              'ITVX',              'Streaming & Video',    true),
  ('pluto.tv',              'Pluto TV',          'Streaming & Video',    true),
  ('tubi.tv',               'Tubi',              'Streaming & Video',    true),
  ('vimeo.com',             'Vimeo',             'Streaming & Video',    true),
  ('dailymotion.com',       'Dailymotion',       'Streaming & Video',    true),
  ('rumble.com',            'Rumble',            'Streaming & Video',    true),

  -- Travel (12)
  ('vrbo.com',              'VRBO',              'Travel',               true),
  ('trivago.com',           'Trivago',           'Travel',               true),
  ('agoda.com',             'Agoda',             'Travel',               true),
  ('hostelworld.com',       'Hostelworld',       'Travel',               true),
  ('momondo.com',           'Momondo',           'Travel',               true),
  ('jet2.com',              'Jet2',              'Travel',               true),
  ('easyjet.com',           'easyJet',           'Travel',               true),
  ('ba.com',                'British Airways',   'Travel',               true),
  ('delta.com',             'Delta',             'Travel',               true),
  ('united.com',            'United Airlines',   'Travel',               true),
  ('lufthansa.com',         'Lufthansa',         'Travel',               true),
  ('emirates.com',          'Emirates',          'Travel',               true),

  -- Social & Community (6)
  ('quora.com',             'Quora',             'Social',               true),
  ('medium.com',            'Medium',            'Social',               true),
  ('substack.com',          'Substack',          'Social',               true),
  ('tumblr.com',            'Tumblr',            'Social',               true),
  ('mastodon.social',       'Mastodon',          'Social',               true),
  ('bluesky.app',           'Bluesky',           'Social',               true),

  -- Security (5)
  ('bitwarden.com',         'Bitwarden',         'Security',             true),
  ('dashlane.com',          'Dashlane',          'Security',             true),
  ('expressvpn.com',        'ExpressVPN',        'Security',             true),
  ('surfshark.com',         'Surfshark',         'Security',             true),
  ('malwarebytes.com',      'Malwarebytes',      'Security',             true),

  -- Logistics & Delivery (8)
  ('fedex.com',             'FedEx',             'Logistics',            true),
  ('ups.com',               'UPS',               'Logistics',            true),
  ('dhl.com',               'DHL',               'Logistics',            true),
  ('royalmail.com',         'Royal Mail',        'Logistics',            true),
  ('evri.com',              'Evri',              'Logistics',            true),
  ('parcelforce.com',       'Parcelforce',       'Logistics',            true),
  ('dpd.co.uk',             'DPD',               'Logistics',            true),
  ('yodel.co.uk',           'Yodel',             'Logistics',            true),

  -- Automotive (5)
  ('autotrader.co.uk',      'AutoTrader',        'Automotive',           true),
  ('carwow.co.uk',          'Carwow',            'Automotive',           true),
  ('cargurus.com',          'CarGurus',          'Automotive',           true),
  ('kbb.com',               'Kelley Blue Book',  'Automotive',           true),
  ('motors.co.uk',          'Motors.co.uk',      'Automotive',           true),

  -- Real Estate (5)
  ('rightmove.co.uk',       'Rightmove',         'Real Estate',          true),
  ('zoopla.co.uk',          'Zoopla',            'Real Estate',          true),
  ('zillow.com',            'Zillow',            'Real Estate',          true),
  ('realtor.com',           'Realtor.com',       'Real Estate',          true),
  ('trulia.com',            'Trulia',            'Real Estate',          true),

  -- Design & Creative (10)
  ('adobe.com',             'Adobe',             'Design & Creative',    true),
  ('sketch.com',            'Sketch',            'Design & Creative',    true),
  ('invisionapp.com',       'InVision',          'Design & Creative',    true),
  ('behance.net',           'Behance',           'Design & Creative',    true),
  ('dribbble.com',          'Dribbble',          'Design & Creative',    true),
  ('unsplash.com',          'Unsplash',          'Design & Creative',    true),
  ('pexels.com',            'Pexels',            'Design & Creative',    true),
  ('shutterstock.com',      'Shutterstock',      'Design & Creative',    true),
  ('gettyimages.com',       'Getty Images',      'Design & Creative',    true),
  ('freepik.com',           'Freepik',           'Design & Creative',    true),

  -- Communication (6)
  ('telegram.org',          'Telegram',          'Communication',        true),
  ('viber.com',             'Viber',             'Communication',        true),
  ('skype.com',             'Skype',             'Communication',        true),
  ('meet.google.com',       'Google Meet',       'Communication',        true),
  ('wire.com',              'Wire',              'Communication',        true),
  ('line.me',               'Line',              'Communication',        true),

  -- Analytics (5)
  ('analytics.google.com',  'Google Analytics',  'Dev Tools',            true),
  ('mixpanel.com',          'Mixpanel',          'Dev Tools',            true),
  ('amplitude.com',         'Amplitude',         'Dev Tools',            true),
  ('hotjar.com',            'Hotjar',            'Dev Tools',            true),
  ('fullstory.com',         'FullStory',         'Dev Tools',            true),

  -- Email & Marketing (6)
  ('sendgrid.com',          'SendGrid',          'Email & Marketing',    true),
  ('klaviyo.com',           'Klaviyo',           'Email & Marketing',    true),
  ('brevo.com',             'Brevo',             'Email & Marketing',    true),
  ('drip.com',              'Drip',              'Email & Marketing',    true),
  ('campaignmonitor.com',   'Campaign Monitor',  'Email & Marketing',    true),
  ('constantcontact.com',   'Constant Contact',  'Email & Marketing',    true),

  -- CDN & Infrastructure (5)
  ('imperva.com',           'Imperva',           'CDN & Infrastructure', true),
  ('maxcdn.com',            'StackPath',         'CDN & Infrastructure', true),
  ('keycdn.com',            'KeyCDN',            'CDN & Infrastructure', true),
  ('jsdelivr.com',          'jsDelivr',          'CDN & Infrastructure', true),
  ('cdnjs.com',             'cdnjs',             'CDN & Infrastructure', true),

  -- Big Tech / Other (8)
  ('ibm.com',               'IBM',               'Other',                true),
  ('intel.com',             'Intel',             'Other',                true),
  ('nvidia.com',            'NVIDIA',            'Other',                true),
  ('qualcomm.com',          'Qualcomm',          'Other',                true),
  ('sony.com',              'Sony',              'Other',                true),
  ('lg.com',                'LG',                'Other',                true),
  ('huawei.com',            'Huawei',            'Other',                true),
  ('spacex.com',            'SpaceX',            'Other',                true)

ON CONFLICT (domain) DO NOTHING;
