-- Migration 97: Add source_calendar_row_id link from blog_posts back to content_calendar
-- =================================================================
-- Closes the calendar-pipeline idempotency gap flagged in the
-- May 2026 audit. Sequence of events that previously caused orphans:
--
--   1. draft-runner claims calendar row → status='generating'
--   2. Generator inserts blog_post (no link back to calendar row)
--   3. Token creation crashes / Vercel retries / 30-min stuck reset
--   4. Calendar row goes back to 'planned'
--   5. Cron re-runs generator on the same row
--   6. Slug generation now collides with the orphan blog_post
--   7. Generator marks the row 'failed' — orphan stranded forever
--
-- With this column, the generator can detect step 6 explicitly:
-- if a blog_post already exists with source_calendar_row_id = row.id,
-- that's an orphan from a prior run — link it to the row instead of
-- regenerating, and let approval tokens be retried.
--
-- The column is also independently useful for traceability / analytics —
-- "which calendar row produced this blog post?" is a one-query lookup.
-- =================================================================

ALTER TABLE public.blog_posts
  ADD COLUMN IF NOT EXISTS source_calendar_row_id UUID
    REFERENCES public.content_calendar(id) ON DELETE SET NULL;

COMMENT ON COLUMN public.blog_posts.source_calendar_row_id IS
  'When this post was generated by the calendar pipeline, references the source content_calendar row. NULL for human-authored posts and outage auto-blogs (which use source_public_incident_id instead). Used by the generator to detect orphans from a crashed prior run and avoid duplicate inserts.';

-- Partial index — only the small set of calendar-sourced posts is indexed.
CREATE INDEX IF NOT EXISTS idx_blog_posts_source_calendar_row
  ON public.blog_posts(source_calendar_row_id)
  WHERE source_calendar_row_id IS NOT NULL;
